language: ruby
cache: bundler
gemfile: docs/Gemfile
before_install:
  - gem install bundler
script:
  - bundle exec jekyll algolia --config ./docs/_config.yml
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
rvm:
  - 2.4
