source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

# octokit 4.x (pulled in via github-pages -> jekyll-github-metadata) breaks on
# faraday 2.x, which removed the bundled default adapter. Pin to faraday 1.x.
gem "faraday", "~> 1.0"

# webrick was removed from Ruby's default gems in Ruby 3.0; Jekyll's local
# server (jekyll serve) needs it.
gem "webrick", "~> 1.8"

gem "tzinfo-data"
gem "wdm", "~> 0.1.0" if Gem.win_platform?

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
  gem "jekyll-feed"
  gem "jemoji"
  gem "jekyll-include-cache"
  gem "jekyll-algolia"
end
